### ISSUE TITLE
Publish on F-Droid

### ISSUE THREAD

**Issue by jonas2515** [pushbit/dining-out#1]
Would be very nice to see this app published in the F-Droid app store.

**Comment by pushbit** [comment]
I have looked into this a few times over the years, but I'm not sure that the app meets F-Droid's [Inclusion Policy][1] because it uses Google services that are not FOSS.  Also, using those Google services requires my private API and package signing keys which aren't included in the repository, for obvious reasons.  So F-Droid would not be able to build a functional version of the application.  These are the reasons that I haven't pursued it further.

[1]: https://f-droid.org/wiki/page/Inclusion_Policy

**Comment by jonas2515** [comment]
Ok, I didn't know the app uses google play services, I'll close the issue.
